version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app1
    working_dir: /app1
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=meubanco
      - DB_USER=usuario
      - DB_PASSWORD=senha123
    depends_on:
      - db
    command: python app.py

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
